### PR TITLE
Trigger animate event

### LINKED ISSUE #10: Fire event when intersection occurs
I would like to have a DOM event fired whenever intersection occurs. It should be trivial to add such functionality. Let me know if you are willing to add, and I can submit a PR for it.

### PR DESCRIPTION
**Pull request by sntran**
Resolves #10.

I had tests for checking `event.detail`, but Puppeteer does not include that property in the event. You just have to take my words for it that `event.detail` is the `IntersectionObserverEntry`.

### CODE REVIEW

**Comment by sntran** [comment]
Also, I was not sure whether to trigger another event when the element is not intersecting (in `reverse` function). Let me know if you would like that.

**Comment by mciastek** [comment]
I think that `CustomEvent` is not the best option in this case. I would prefer adding a callback property to `sal.js` options like `onEnter` and `onExit`, which will allow to track what element is currently in viewport, etc. [CustomEvent API](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent) is not widely supported, so to run sal.js on Safari you would need to add 2 polyfills, which is too much in my opinion.

**Comment by sntran** [comment]
Using callback only allows 1 handler at a time. Having event allows multiple listeners. Also, having the event originated from the elements in viewport feels more natural to me than checking for desired elements in a single callback.

Polyfill for `CustomEvent` is very tiny. I'd rather patch things up for less used browsers than trying to accommodate them with outdated technique.

Besides, https://caniuse.com/#feat=customevent shows a better compatibility table for Safari.

**Comment by mciastek** [comment]
As I see in [Browser compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent#Browser_compatibility), Safari doesn't support constructor of `CustomEvent` and `detail` property, which you use to provide entry's context. Please test it on Safari (preferably on 11th version) and confirm that it works properly.

Also I think that, it's a nice idea to add both `enter` and `exit` events, followed by `sal` prefix. So I would propose something like `sal:enter` and `sal:exit` for event names. I don't think that event name needs to be customisable.

Please also remember, that adding `CustomEvent` to sal.js requires proper note in documentation, especially about required polyfill.

**Comment by sntran** [comment]
The MDN's browser compatibility table only shows Safari 5.1. The current version of Safari is 12.0. And with most people on Mac OSX, their Safari is very up to date.

Here is the [test](https://codepen.io/anon/pen/ZmdWZb) I used to test on Safari 12.0, and it works fine.

Regardless, since a polyfill is required any way for IE, Safari should be taken care of.

Regard documentation, I don't think asking the user to include the polyfill is nice. We can simply include the following [polyfill snippet](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill) in sal.js codebase:

```js
(function () {

  if ( typeof window.CustomEvent === "function" ) return false;

  function CustomEvent ( event, params ) {
    params = params || { bubbles: false, cancelable: false, detail: undefined };
    var evt = document.createEvent( 'CustomEvent' );
    evt.initCustomEvent( event, params.bubbles, params.cancelable, params.detail );
    return evt;
   }

  CustomEvent.prototype = window.Event.prototype;

  window.CustomEvent = CustomEvent;
})();
```

**Comment by mciastek** [comment]
Ok, I see that Safari is covered. As sal.js is based on IntersectionObserver, we need to adjust browser support to this API. In other words, we may not need polyfill for `CustomEvent` as you said that it's valid only for IE, which we don't support at all.

What about this one?
>Also I think that, it's a nice idea to add both enter and exit events, followed by sal prefix. So I would propose something like sal:enter and sal:exit for event names. I don't think that event name needs to be customisable.

**Comment by mciastek** [comment]
I'm merging this PR. It needs a few adjustments and then I will release it. Thanks!

**Comment by sntran** [comment]
Sorry, I somehow missed your comment. I could add those events with prefix if you would like.

I would also like to suggest "sal:in" and "sal:out" instead, to match with `aos`.

**Comment by mciastek** [comment]
Thanks for suggestion. I have added it.

**Pull request merged**
