### PR TITLE
Support standard threshold option

### PR DESCRIPTION
**Pull request by sntran**
Can take either single value or an array of them, just as the Intersection Observer.

Also, switch to check `entry.isIntersecting` instead of comparing
against the threshold.

### CODE REVIEW

**Comment by mciastek** [comment]
What is a use case of updated `threshold` option. The idea behind `sal.js` is to have an abstraction upon Intersection Observer API, which allows you to easily animate elements on scroll. Adding more options and giving full access to Intersection Observer options is not a goal of this library.

**Comment by sntran** [comment]
This new `threshold` option is actually related to #11 , in which I need to know how much of intersection that occurs. Think parallax effect. Having a single number for `threshold` means I only know once when the intersection occurs.

I'm not adding more option or giving full access to IO here. Just make one existing option more usable.

**Comment by mciastek** [comment]
> Think parallax effect. Having a single number for threshold means I only know once when the intersection occurs.

I think that sal.js is proper library to make parallax effect. Sal it's fine for simple in-out animation on scroll position. To be honest, I don't see a good use case for extended `threshold` option, and I think it can introduce some misunderstandings.

**Comment by sntran** [comment]
Sure. I'll close this. However, I would like to see an example of parallax with sal.js.

**Pull request closed without merging**
